### ISSUE TITLE
Failed to resolve: com.appnext.sdk:appnext-sdk:2.+

### ISSUE THREAD

**Issue by ShibinCo** [Muneefm/YIFY-Client-Android-App#1]
Error !

**Comment by ShibinCo** [comment]
Could you please push the latest commit?

**Comment by Muneefm** [comment]
This issue must be causing due to the appnext sdk, its an ad monitisation platform if you are not using them you can just remove it from gradles and also from the imports.  let me know it solved your issue.  also you can push your latest commits here.

**Comment by ShibinCo** [comment]
Issue resolved !
Thanks @Muneefm

**Comment by mahdi-malv** [comment]
Same issue here.

**Comment by Muneefm** [comment]
@mahdi-malv you can remove appnext dependency from gradle and Java classes. and then clean and rebuild project.
